export const categoriesToSelect = [
  'Serviço Automotivo',
  'Bebidas',
  'Bichos de Estimação',
  'Biscoitos',
  'Congelados',
  'Enlatados',
  'Ferramentas de Limpeza',
  'Higiene Pessoal',
  'Jardinagem',
  'Pet Food',
  'Suplementos',
  'Grãos e Cereais',
  'Doces',
  'Legumes',
  'Carne',
  'Massas',
  'Laticinios',
  'Frutas',
];
